
DROP TABLE IF EXISTS t_PACKAGE1_MODULE_;
CREATE TABLE t_PACKAGE1_MODULE_
(
  c_id CHAR(36) NOT NULL COMMENT '主键',DDL_COLUMNS

  PRIMARY KEY pk_PACKAGE1_MODULE_(c_id)DDL_KEYS
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
